# React build
FROM node:24.14.1-alpine AS frontend
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

# Go build
FROM golang:1.26-alpine AS backend
WORKDIR /app/backend
COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend/internal ./internal
COPY backend/cmd ./cmd

# Reactでビルドした成果物をGoにコピー
COPY --from=frontend /app/frontend/dist ./cmd/dist

RUN CGO_ENABLED=0 GOOS=linux go build -tags=prod -v -o ./cmd ./cmd

# aplpineで最小イメージを作成
FROM alpine:3.23.4

# 非ルートユーザの作成
RUN addgroup -S osint && adduser -S user -G osint
USER user

WORKDIR /app
COPY --from=backend /app/backend/cmd .
EXPOSE 4000
CMD ["./cmd"]